### ISSUE TITLE
ImportError in Evaluation_Analysis.ipynb 

### ISSUE THREAD

**Issue by APratham** [aws-deepracer-community/deepracer-analysis#13]
I am getting an `ImportError` for `CloudWatchLogs` when I try to run the Evaluation_Analysis Jupyter notebook. Kindly look into it and please let me know if there are any changes that I can do so the script works 

![image (3)](https://user-images.githubusercontent.com/33273990/108794459-c632af80-75ab-11eb-9c07-ff55e188cc41.png)

**Comment by APratham** [comment]
## Suggested workaround
By _Jochem Lugtenburg_


Import DeepRacerLog class and use that instead of CloudWatchLogs

**Comment by larsll** [comment]
The overall bug here is that the Evaluation_Analysis.ipynb has not been updated as the log file format has been updated. Also `logs/deepracer-eval-sim-sample.log` and `logs/deepracer-sim-sample.log` are having a wrong format.

I am generating a new sample model with log files to base the file update on.
