### ISSUE TITLE
what's the default password for jovyan

### ISSUE THREAD

**Issue by AdrainHuang** [aws-deepracer-community/deepracer-analysis#24]
I use docker image to start the deepracer-analysis. I tried jovyan and juypter. But it doesn't work.
![image](https://user-images.githubusercontent.com/20974682/135193075-22e61ecc-c7c5-45b4-b704-9258bee1185a.png)

**Comment by larsll** [comment]
See here: https://github.com/kubeflow/kubeflow/issues/425

**Comment by harraz** [comment]
any updates here? I have the same issue. Thanks!
