### ISSUE TITLE
Analysis not working with latest deepracer cloud

### ISSUE THREAD

**Issue by rsrini7** [aws-deepracer-community/deepracer-analysis#29]
Analysis not supported with latest deepracer cloud [deepracer-for-cloud](https://github.com/aws-deepracer-community/deepracer-for-cloud)

expects csv file, but found folders
IsADirectoryError: [Errno 21] Is a directory: '/home/srini/deepracer-for-cloud/data/minio/bucket/rl-deepracer-sagemaker/training-simtrace/1-iteration.csv'

![image](https://user-images.githubusercontent.com/5178105/178103807-77242c1a-fe2f-458f-908b-be57de81614b.png)

**Comment by 20000031725** [comment]
![16587686770935555586351352209939](https://user-images.githubusercontent.com/96175548/180834634-4f869b9a-a0d2-4738-a3db-60ccca941968.jpg)
Please send me finial assessment answers for deepRacer

**Comment by larsll** [comment]
This is 'known' -- lastest version of Minio no longer stores files cleanly on disk. You have two options:
* Install version 1.0.0 of deepracer-utils (released today) and download via S3 bucket
* Go into the minio console and download the files you want into a folder and then analyze from there.
