### ISSUE TITLE
log.load() returns file not found

### ISSUE THREAD

**Issue by Sheldenburg** [aws-deepracer-community/deepracer-analysis#32]
When I used the training_analysis.ipynb notebook. It returns me an error at log.load()

I'm using the example code, haven't changed anything. Think this log.load() utility function has been updated recently in another repo? can someone please advise what's the correct file structure now? thanks!!

![image](https://user-images.githubusercontent.com/18107058/184993570-bdcd11ab-aea9-442a-b225-2bf8852711a1.png)

**Comment by larsll** [comment]
@Sheldenburg - which container are you using? The one distributed with DRfC?

**Comment by jhtut** [comment]
Hi, 

Faced the same issue.  I'm just following the README.md from repo https://github.com/aws-deepracer-community/deepracer-analysis and using the docker that was newly build via "bin/build-docker-image.sh".  You might want it give it a go to get the latest docker image built.

**Comment by anjrew** [comment]
I am also getting this error

**Comment by HasarinduPerera** [comment]
Anyone found any solution to this? (Using the notebooks without Docker)

TIA

**Comment by larsll** [comment]
The issue is that it tries to load the trace logs, not the robomaker logs -- but in this repository the model_metadata.json is missing.
