### ISSUE TITLE
Can't load the logs - load_robomaker_logs()

### ISSUE THREAD

**Issue by ribeiro1505** [aws-deepracer-community/deepracer-analysis#35]
To train DeepRacer locally, I've been following this tutorial on Youtube. After successfully training the model, I wanted to see some logs.

After following the README file instructions, the logs can't be loaded. Error on image below

I've also tried different path locations, but nothing seems to work.

<img width="892" alt="Screenshot 2022-11-27 at 10 48 25" src="https://user-images.githubusercontent.com/44843960/204131271-e8005eeb-5c06-49f4-98cc-1b298c3594ba.png">

**Comment by larsll** [comment]
I suggest asking questions in Slack https://aws-ml-community.slack.com/ssb/redirect, response to questions is faster there.

The issue is related to https://github.com/aws-deepracer-community/deepracer-utils/issues/43.

Suggest to use `log.load_training_trace()`

**Comment by larsll** [comment]
Latest version of workbook + deepracer-utils will prevent this from happen.
