### ISSUE TITLE
Update Workbooks to optionally read from S3

### ISSUE THREAD

**Issue by larsll** [aws-deepracer-community/deepracer-analysis#37]
The analysis workbooks need updating. Currently there is references to old ways of obtaining logs (e.g. CloudWatch). We should move towards latest ways of reading logs; e.g. as documented here https://github.com/aws-deepracer-community/deepracer-utils/blob/master/docs/examples.md.

Most important part of the feature is ability to read from a local minio via the S3 interface.

**Comment by MarkitectRoss** [comment]
Hopefully PR addresses what's needed now - https://github.com/aws-deepracer-community/deepracer-analysis/pull/43

**Comment by larsll** [comment]
Fixed via #43 and #45
