### ISSUE TITLE
Download deepracer for cloud logs in correct format

### ISSUE THREAD

**Issue by MarkitectRoss** [aws-deepracer-community/deepracer-analysis#38]
Hi Lars,

I've written a script for Deep Racer for Cloud logs to be pulled down and manipulated into a format the analysis notebook supports but I can't create a branch and send you a PR for review.  Hope it's useful: -

cd logs
if [[ $# != 2 ]] ; then
  echo 'USAGE: .bin/get-dr-on-the-spot-logs.sh s3://your_bucket/your_log_location logs/local_folder_to_copy_to'
  exit 0
fi
echo "Copying Deep Racer logs from S3 to local for Log analysis"
echo "Copying from $1"
echo "Copying to $2"
echo "If it doesn't work correctly drop the final / from $1"
mkdir $2
#Copy logs and metrics
aws s3 cp $1/logs $2/logs/training --recursive
aws s3 cp $1/metrics $2/metrics/training --recursive
#Manipulate robomaker container log names so as not to overwrite the logs from each worker when using multiple robomaker containers
COUNTER=$(aws s3 ls $1 | grep [0-9]/ -c)
COUNTER=$(($COUNTER+1))
for i in `seq 1 $COUNTER`;
do
  for file in $(ls $2/logs/training/*robomaker.$i.*.log)
  do
   mv -T $file "${file%%.*.*}"$i-"robomaker.""${file##*.}"
 done
done
#Manipulate log names for sim-trace so as not to overwrite the logs from each worker when using multiple robomaker containers
#aws s3 cp $1/training-simtrace $2/sim-trace/training/training-simtrace --recursive
for dir in $(aws s3 ls $1/ | grep [0-9]/ | sed 's/PRE//g;s/.$//')
do
  echo "copying $1/$dir/training-simtrace to $2/sim-trace/training/training-simtrace"
  aws s3 cp $1/$dir/training-simtrace $2/sim-trace/training/training-simtrace --recursive
  for file in $(ls $2/sim-trace/training/training-simtrace/*iteration.csv)
  do
    mv -T $file "${file%%.*.*}"-worker$dir."${file##*.}"
  done
done
cd ..

**Comment by larsll** [comment]
I am not sure if this is really needed - there are means to slurp log-files directly out of S3 (or even the Console during running training). -- https://github.com/aws-deepracer-community/deepracer-utils/blob/master/docs/examples.md

The real job that needs doing is to embed that into the workbooks -- see also #37

**Comment by MarkitectRoss** [comment]
Fair point, hadn't realised that other option existed, will give it a try.
