### ISSUE TITLE
Evaluation_analysis.ipynb seems to have some versioning issues with pandas.

### ISSUE THREAD

**Issue by NotSinan** [aws-deepracer-community/deepracer-analysis#41]
The following line in the Jupyter Notebook throws an error:

bulk = slio.load_a_list_of_logs(logs) 

The error is as follows: 
    208             eval_data = SimulationLogsIO.load_data(log[0])
    209             dataframe = SimulationLogsIO.convert_to_pandas(eval_data)
    210             dataframe['stream'] = log[1]
    211             if full_dataframe is not None:
--> 212                 full_dataframe = full_dataframe.append(dataframe)
    213             else:
    214                 full_dataframe = dataframe

AttributeError: 'DataFrame' object has no attribute 'append'

I am using the sample-console-logs (doing this on my local environment). 

Please let me know if further information is needed.

**Comment by larsll** [comment]
The issue occurs if you are using Pandas 2.0. Now we need to change it to use `concat`.

As a workaround try to have `full_dataframe = pd.concat([full_dataframe, dataframe], ignore_index=True)`

**Comment by larsll** [comment]
This was resolved via https://github.com/aws-deepracer-community/deepracer-utils/pull/52 (deepracer-utils 1.0.6).

It is now available in the latest docker images.
